from Tkinter import Tk,Label,Button,Entry,Text,Radiobutton,IntVar,OptionMenu,StringVar
from Tkinter import *

def startapp():
    root1 = Tk()
    root1.geometry('300x300')
    root1.title('Rappel')
    label1 = Label(root1,text = 'Hi..Welcome To Our Project RAPPEL..!!',font = 'bold')
    label1.pack()
    button1 = Button(root1,text = 'Get Started',font = 'bold',command = homepage)
    button1.pack()
    pic = PhotoImage(file = 'hi.png')
    label2 = Label(root1,image = pic)
    label2.pack()
    root1.mainloop()
    
def homepage():
    root2 = Tk()
    root2.title('Homepage')
    l1 = Label(root2,text = '-: Menu :-',font = 'bold')
    l1.pack()
    b1 = Button(root2,text = 'Add Birthday',font = 'bold',command = birthday)
    b1.pack()
    b2 = Button(root2,text = 'Add Anniversery',font = 'bold',command = anniversery)
    b2.pack()
    b3 = Button(root2,text = 'Check for remainder',font = 'bold')
    b3.pack()
    b4 = Button(root2,text = 'Exit',font = 'bold',command = close)
    b4.pack()
    root2.mainloop()

def birthday():
    root3 = Tk()
    root3.title('Birthday')  
    name = Label(root3,text = 'Enter the name : ',font = 'bold')
    name.pack()
    e1 = Entry(root3)
    e1.pack()
    n1 = e1.get()
    date = Label(root3,text = 'Enter the date (yyyy-mm-dd) : ',font = 'bold')
    date.pack()
    e2 = Entry(root3)
    e2.pack()
    d1 = e2.get()
    mail = Label(root3,text = 'Enter the Mail Id : ',font = 'bold')
    mail.pack()
    e3 = Entry(root3)
    e3.pack()
    m1 = e3.get()
    f1 = open("b1.txt",'a')
    f1.write(n1)
    f1.write(",")
    f1.write(d1)
    f1.write(",")
    f1.write(m1)
    f1.write("\n")
    b = Button(root3,text = 'Add birthday',font = 'bold',command = homepage)
    b.pack()
    #p = Label(root4,"\nBirthday added sucessfully..!!")
    #p.pack()
    root3.mainloop()

def anniversery():
    root4 = Tk()
    root4.title('Anniversery')  
    name1 = Label(root4,text = 'Enter first name : ',font = 'bold')
    name1.pack()
    e_name1 = Entry(root4)
    e_name1.pack()
    name_1 = e_name1.get()
    name2 = Label(root4,text = 'Enter second name : ',font = 'bold')
    name2.pack()
    e_name2 = Entry(root4)
    e_name2.pack()
    name_2 = e_name2.get()
    dat = Label(root4,text = 'Enter the date (yyyy-mm-dd) : ',font = 'bold')
    dat.pack()
    e_date = Entry(root4)
    e_date.pack()
    dat1 = e_date.get()
    email = Label(root4,text = 'Enter the Mail Id : ',font = 'bold')
    email.pack()
    e_mail = Entry(root4)
    e_mail.pack()
    mail_1 = e_mail.get()
    f2 = open("a1.txt",'a')
    f2.write(name_1)
    f2.write(" ")
    f2.write(name_2)
    f2.write(",")
    f2.write(dat1)
    f2.write(",")
    f2.write(mail_1)
    f2.write("\n")
    c = Button(root4,text = 'Add anniversery',font = 'bold',command = homepage)
    c.pack()
    #p = Label(root4,"\nBirthday added sucessfully..!!")
    #p.pack()
    root4.mainloop()
    
#def remainder():
    
def close():
    r1 = Tk()
    a = Label(r1,text = 'You are exiting from the program..!!',font = 'bold')
    a.pack()
    r1.mainloop()
    exit(0)
    
startapp()